### ISSUE TITLE
Fid calculation 

### ISSUE THREAD

**Issue by prinshul** [HKU-MedAI/GEM-3D#1]
How are you calculating Fid on test data?

**Comment by Advocate99** [comment]
Hi, we compute FID based on 2D slices. 
To convey the 3D similarity information, we get slices from 3 views, as discusssed in the paper.

**Comment by prinshul** [comment]
And which backbone/model is used?

**Comment by Advocate99** [comment]
We use resnet50 pretrained on radimagenet. 

network = torch.hub.load("Warvito/radimagenet-models", model="radimagenet_resnet50", verbose=True)

Here are some related links:
https://github.com/Project-MONAI/GenerativeModels/blob/main/generative/metrics/fid.py
https://github.com/BMEII-AI/RadImageNet
